apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cuenta-movimiento-backend
    app.kubernetes.io/name: cuenta-movimiento-backend
    #app.kubernetes.io/name: cuenta-movimiento-backend
  name: cuenta-movimiento-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cuenta-movimiento-backend
  template:
    metadata:
      labels:
        app: cuenta-movimiento-backend
    spec:
      containers:
        - name: cuenta-movimiento-backend
          image: CONFIG_LOCATION-docker.pkg.dev/CONFIG_PROJECT_ID/CONFIG_SERVICE/CONFIG_APP_NAME-CONFIG_ENVIRONMENT:CONFIG_VERSION
          resources:
            limits:
              memory: 1Gi
              cpu: 500m
            requests:
              memory: 500Mi
              cpu: 250m
          ports:
            - containerPort: 3000
            - containerPort: 9229
          #env:
          #  - NODE_ENV: 
          envFrom:
            - configMapRef:
                name: env-cuenta-movimiento-backend
          volumeMounts:
            - name: env-cuenta-movimiento-backend-volume
              mountPath: /usr/app/properties.env
              subPath: properties.env
      volumes:
        - name: env-cuenta-movimiento-backend-volume
          configMap:
            name: env-cuenta-movimiento-backend
