apiVersion: v1
kind: Service
metadata:
  labels:
    app: cuenta-movimiento-backend
  name: cuenta-movimiento-backend-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: cuenta-movimiento-backend
  type: LoadBalancer
